(DEFUN POP-UP-WINDOW (LIFE-TIME &OPTIONAL (HOST ""))
  (LET* ((DISPLAY (XLIB:OPEN-DISPLAY HOST))
         (SCREEN (FIRST (XLIB:DISPLAY-ROOTS DISPLAY)))
         (ROOT-WINDOW (XLIB:SCREEN-ROOT SCREEN))
         (MY-WINDOW
          (XLIB:CREATE-WINDOW :PARENT ROOT-WINDOW :X 0 :Y 0 :WIDTH 200 :HEIGHT
                              100)))
    (XLIB:MAP-WINDOW MY-WINDOW)
    (XLIB:DISPLAY-FINISH-OUTPUT DISPLAY)
    (FORMAT T "should appear now~%")
    (SLEEP LIFE-TIME)
    (XLIB:DESTROY-WINDOW MY-WINDOW)
    (XLIB:CLOSE-DISPLAY DISPLAY)))